/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantemployeesystem;

import java.awt.Cursor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static restaurantemployeesystem.Database.con;

/**
 *
 * @author User
 */
public class EmployeeRegistry extends javax.swing.JFrame {

    /**
     * Creates new form User
     */
    public EmployeeRegistry() {
        initComponents();
        
        btnBack.setOpaque(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setBorderPainted(false);
        btnBack.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        txtAddress.setCursor(Cursor.getPredefinedCursor(Cursor.TEXT_CURSOR));
        txtDateHired.setCursor(Cursor.getPredefinedCursor(Cursor.TEXT_CURSOR));
        txtEmpCode.setCursor(Cursor.getPredefinedCursor(Cursor.TEXT_CURSOR));
        txtFName.setCursor(Cursor.getPredefinedCursor(Cursor.TEXT_CURSOR));
        txtLName.setCursor(Cursor.getPredefinedCursor(Cursor.TEXT_CURSOR));
        txtSalary.setCursor(Cursor.getPredefinedCursor(Cursor.TEXT_CURSOR));
        txtMobileNo.setCursor(Cursor.getPredefinedCursor(Cursor.TEXT_CURSOR));
        txtSearch.setCursor(Cursor.getPredefinedCursor(Cursor.TEXT_CURSOR));
        comboSearch.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        comboStatus.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btAdd.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btDelete.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btSearch.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btUpdate.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        Table();
    }
    
    public void Table(){
        
        try{
            
            Database db = new Database();
            db.getDatabaseConnection();
            PreparedStatement ps = con.prepareStatement("SELECT * FROM employee_registry");
            ResultSet rs = ps.executeQuery();
            DefaultTableModel dtm = (DefaultTableModel)tblDetails.getModel();
            dtm.setRowCount(0);
            
            while(rs.next())
            {
                Object o[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)};
                dtm.addRow(o);
            }
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btDelete = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btAdd = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        comboSearch = new javax.swing.JComboBox<>();
        btSearch = new javax.swing.JButton();
        txtEmpCode = new javax.swing.JTextField();
        txtFName = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtMobileNo = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        txtDateHired = new javax.swing.JTextField();
        comboStatus = new javax.swing.JComboBox<>();
        lblStatus = new javax.swing.JLabel();
        lblDateHired = new javax.swing.JLabel();
        lblSalary = new javax.swing.JLabel();
        lblMobileNo = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblEmployeeCode = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetails = new javax.swing.JTable();
        EmployeeRegistration = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        BlackStrap = new javax.swing.JLabel();
        GreyBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Registry");
        setIconImages(null);
        setMaximumSize(new java.awt.Dimension(970, 690));
        setMinimumSize(new java.awt.Dimension(970, 690));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btDelete.setBackground(new java.awt.Color(204, 204, 204));
        btDelete.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        btDelete.setText("DELETE");
        getContentPane().add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 310, -1, -1));

        btUpdate.setBackground(new java.awt.Color(204, 204, 204));
        btUpdate.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        btUpdate.setText("UPDATE");
        getContentPane().add(btUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, -1, -1));

        btAdd.setBackground(new java.awt.Color(204, 204, 204));
        btAdd.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        btAdd.setText("ADD");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        getContentPane().add(btAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, -1, -1));

        txtSearch.setFont(new java.awt.Font("Bernard MT Condensed", 0, 16)); // NOI18N
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 260, -1));

        comboSearch.setFont(new java.awt.Font("Bernard MT Condensed", 0, 16)); // NOI18N
        comboSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee ID", "First Name", "Last Name", "Address", "Mobile No", "Monthly Salary", "Date Hired", "Status" }));
        getContentPane().add(comboSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 130, -1));

        btSearch.setBackground(new java.awt.Color(204, 204, 204));
        btSearch.setFont(new java.awt.Font("Bernard MT Condensed", 0, 16)); // NOI18N
        btSearch.setText("SEARCH");
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        txtEmpCode.setFont(new java.awt.Font("Bernard MT Condensed", 0, 16)); // NOI18N
        getContentPane().add(txtEmpCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 120, -1));

        txtFName.setFont(new java.awt.Font("Bernard MT Condensed", 0, 16)); // NOI18N
        getContentPane().add(txtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 260, -1));

        txtLName.setFont(new java.awt.Font("Bernard MT Condensed", 0, 16)); // NOI18N
        getContentPane().add(txtLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 260, -1));

        txtAddress.setFont(new java.awt.Font("Bernard MT Condensed", 0, 16)); // NOI18N
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 260, -1));

        txtMobileNo.setFont(new java.awt.Font("Bernard MT Condensed", 0, 16)); // NOI18N
        getContentPane().add(txtMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 260, -1));

        txtSalary.setFont(new java.awt.Font("Bernard MT Condensed", 0, 16)); // NOI18N
        getContentPane().add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 120, -1));

        txtDateHired.setFont(new java.awt.Font("Bernard MT Condensed", 0, 16)); // NOI18N
        getContentPane().add(txtDateHired, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 260, -1));

        comboStatus.setFont(new java.awt.Font("Bernard MT Condensed", 0, 16)); // NOI18N
        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Full-Time", "Part-Time", "Inactive" }));
        comboStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStatusActionPerformed(evt);
            }
        });
        getContentPane().add(comboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 120, 30));

        lblStatus.setFont(new java.awt.Font("Bernard MT Condensed", 0, 16)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblStatus.setText("Status:");
        getContentPane().add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 50, 30));

        lblDateHired.setFont(new java.awt.Font("Bernard MT Condensed", 0, 16)); // NOI18N
        lblDateHired.setForeground(new java.awt.Color(255, 255, 255));
        lblDateHired.setText("Date Hired:");
        getContentPane().add(lblDateHired, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 100, 30));

        lblSalary.setFont(new java.awt.Font("Bernard MT Condensed", 0, 16)); // NOI18N
        lblSalary.setForeground(new java.awt.Color(255, 255, 255));
        lblSalary.setText("Monthly Salary:");
        getContentPane().add(lblSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 120, 100, 30));

        lblMobileNo.setFont(new java.awt.Font("Bernard MT Condensed", 0, 16)); // NOI18N
        lblMobileNo.setForeground(new java.awt.Color(255, 255, 255));
        lblMobileNo.setText("Mobile No:");
        getContentPane().add(lblMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, -1, -1));

        lblAddress.setFont(new java.awt.Font("Bernard MT Condensed", 0, 16)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress.setText("Address:");
        getContentPane().add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        lblLastName.setFont(new java.awt.Font("Bernard MT Condensed", 0, 16)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblLastName.setText("Last Name:");
        getContentPane().add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        lblFirstName.setFont(new java.awt.Font("Bernard MT Condensed", 0, 16)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName.setText("First Name:");
        getContentPane().add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        lblEmployeeCode.setFont(new java.awt.Font("Bernard MT Condensed", 0, 16)); // NOI18N
        lblEmployeeCode.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployeeCode.setText("Employee ID:");
        getContentPane().add(lblEmployeeCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 90, -1));

        tblDetails.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        tblDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "First Name", "Last Name", "Address", "Mobile No", "Salary", "Date Hired", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDetails);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 950, 270));

        EmployeeRegistration.setFont(new java.awt.Font("Bernard MT Condensed", 0, 28)); // NOI18N
        EmployeeRegistration.setForeground(new java.awt.Color(240, 240, 240));
        EmployeeRegistration.setText("Employee Registry");
        getContentPane().add(EmployeeRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 50));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 50));

        BlackStrap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black screen.jpg"))); // NOI18N
        BlackStrap.setText("jLabel2");
        getContentPane().add(BlackStrap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 50));

        GreyBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown.jpg"))); // NOI18N
        GreyBackground.setText("jLabel1");
        getContentPane().add(GreyBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void comboStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboStatusActionPerformed

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSearchActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        AdminMenu admenu = new AdminMenu();
        admenu.setVisible(true);
        admenu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegistry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegistry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegistry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegistry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeRegistry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BlackStrap;
    private javax.swing.JLabel EmployeeRegistration;
    private javax.swing.JLabel GreyBackground;
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btSearch;
    private javax.swing.JButton btUpdate;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> comboSearch;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblDateHired;
    private javax.swing.JLabel lblEmployeeCode;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMobileNo;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblDetails;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDateHired;
    private javax.swing.JTextField txtEmpCode;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtMobileNo;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
