/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantemployeesystem;

import java.awt.Cursor;

/**
 *
 * @author User
 */
public class Ordering extends javax.swing.JFrame {

    /**
     * Creates new form User
     */
    public Ordering() {
        initComponents();
        
        btnBack.setOpaque(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setBorderPainted(false);
        btnBack.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        cmboFCategory.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnView.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        txtQty.setCursor(Cursor.getPredefinedCursor(Cursor.TEXT_CURSOR));
        btnAdd.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnDelete.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnEdit.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnExit.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnOrder.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnReset.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));




    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        txtFCode = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtFName = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        lblQty = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        lblPrice = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        lblFName = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblMDetails = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        lblODetails = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lblFCode = new javax.swing.JLabel();
        txtOrderNo = new javax.swing.JTextField();
        lblOrderNo = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        lblFCategory = new javax.swing.JLabel();
        cmboFCategory = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblBillingSystem = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        BlackStrap = new javax.swing.JLabel();
        GreyBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ordering System");
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(930, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(java.awt.Color.gray);
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 10, 260));

        jSeparator1.setBackground(java.awt.Color.gray);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 930, 10));

        txtFCode.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        txtFCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFCodeActionPerformed(evt);
            }
        });
        getContentPane().add(txtFCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 100, -1));

        txtPrice.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 100, -1));

        txtFName.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        txtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 230, -1));

        txtQty.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        getContentPane().add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 100, -1));

        lblQty.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        lblQty.setForeground(new java.awt.Color(255, 255, 255));
        lblQty.setText("Quantity:");
        getContentPane().add(lblQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        btnDelete.setBackground(new java.awt.Color(204, 204, 204));
        btnDelete.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, -1, -1));

        lblPrice.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblPrice.setText("Price:");
        getContentPane().add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        btnReset.setBackground(new java.awt.Color(204, 204, 204));
        btnReset.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, -1, -1));

        lblFName.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        lblFName.setForeground(new java.awt.Color(255, 255, 255));
        lblFName.setText("Food Name:");
        getContentPane().add(lblFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        btnExit.setBackground(new java.awt.Color(204, 204, 204));
        btnExit.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 340, -1, -1));

        lblMDetails.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        lblMDetails.setForeground(new java.awt.Color(255, 255, 255));
        lblMDetails.setText("Menu Details");
        getContentPane().add(lblMDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        btnAdd.setBackground(new java.awt.Color(204, 204, 204));
        btnAdd.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        lblODetails.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        lblODetails.setForeground(new java.awt.Color(255, 255, 255));
        lblODetails.setText("Order Details");
        getContentPane().add(lblODetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, -1));

        btnEdit.setBackground(new java.awt.Color(204, 204, 204));
        btnEdit.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        btnEdit.setText("EDIT");
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, -1, -1));

        btnOrder.setBackground(new java.awt.Color(204, 204, 204));
        btnOrder.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        btnOrder.setText("ORDER");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Food Code", "Food Name", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 470, 220));

        lblFCode.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        lblFCode.setForeground(new java.awt.Color(255, 255, 255));
        lblFCode.setText("Food Code:");
        getContentPane().add(lblFCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        txtOrderNo.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        txtOrderNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderNoActionPerformed(evt);
            }
        });
        getContentPane().add(txtOrderNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 100, 30));

        lblOrderNo.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        lblOrderNo.setForeground(new java.awt.Color(255, 255, 255));
        lblOrderNo.setText("Order No:");
        getContentPane().add(lblOrderNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, -1, 30));

        btnView.setBackground(new java.awt.Color(204, 204, 204));
        btnView.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        btnView.setText("View ");
        getContentPane().add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        lblFCategory.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        lblFCategory.setForeground(new java.awt.Color(255, 255, 255));
        lblFCategory.setText("Food Catergory:");
        getContentPane().add(lblFCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        cmboFCategory.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        cmboFCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Main Dishes", "Desserts", "Drinks" }));
        cmboFCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboFCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(cmboFCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, 30));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Food Code", "Food Name", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 410, 220));

        lblBillingSystem.setFont(new java.awt.Font("Bernard MT Condensed", 0, 28)); // NOI18N
        lblBillingSystem.setForeground(new java.awt.Color(240, 240, 240));
        lblBillingSystem.setText("Ordering System");
        getContentPane().add(lblBillingSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 50));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 50));

        BlackStrap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black screen.jpg"))); // NOI18N
        BlackStrap.setText("jLabel2");
        getContentPane().add(BlackStrap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 50));

        GreyBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brown.jpg"))); // NOI18N
        GreyBackground.setText("jLabel1");
        getContentPane().add(GreyBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void cmboFCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboFCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmboFCategoryActionPerformed

    private void txtFCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFCodeActionPerformed

    private void txtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNameActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        Billing bill = new Billing();
        bill.setVisible(true);
        bill.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtOrderNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderNoActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ordering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ordering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ordering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ordering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ordering().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BlackStrap;
    private javax.swing.JLabel GreyBackground;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> cmboFCategory;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblBillingSystem;
    private javax.swing.JLabel lblFCategory;
    private javax.swing.JLabel lblFCode;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblMDetails;
    private javax.swing.JLabel lblODetails;
    private javax.swing.JLabel lblOrderNo;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQty;
    private javax.swing.JTextField txtFCode;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtOrderNo;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables
}
