package restaurantemployeesystem;

import java.awt.Color;
import java.awt.Cursor;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class SignUp extends javax.swing.JFrame {

    public SignUp() {
        initComponents();
      
       
        txtsUserName.setCursor(Cursor.getPredefinedCursor(Cursor.TEXT_CURSOR));
        txtsPassword.setCursor(Cursor.getPredefinedCursor(Cursor.TEXT_CURSOR));
        txtCPassword.setCursor(Cursor.getPredefinedCursor(Cursor.TEXT_CURSOR));
        comboUserType.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
       
        btnBack.setOpaque(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setBorderPainted(false);
        btnBack.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        comboUserType.setBackground(Color.WHITE);
        btnSignUp.setOpaque(false);
        btnSignUp.setContentAreaFilled(false);
        btnSignUp.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        btnExit.setOpaque(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user_icon = new javax.swing.JLabel();
        lblSignUp = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        txtsUserName = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();
        lblUserType = new javax.swing.JLabel();
        lblCPassword = new javax.swing.JLabel();
        comboUserType = new javax.swing.JComboBox<>();
        txtCPassword = new javax.swing.JPasswordField();
        txtsPassword = new javax.swing.JPasswordField();
        btnBack = new javax.swing.JButton();
        lblUserName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usericon.png"))); // NOI18N
        getContentPane().add(user_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        lblSignUp.setFont(new java.awt.Font("Bernard MT Condensed", 0, 36)); // NOI18N
        lblSignUp.setForeground(new java.awt.Color(255, 255, 255));
        lblSignUp.setText("Sign Up");
        getContentPane().add(lblSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 110, -1));

        lblPassword.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password :");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        btnExit.setBackground(new java.awt.Color(0, 0, 0));
        btnExit.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, -1, 30));

        txtsUserName.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        txtsUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsUserNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtsUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 190, 30));

        btnSignUp.setBackground(new java.awt.Color(0, 0, 0));
        btnSignUp.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, -1, 30));

        lblUserType.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        lblUserType.setForeground(new java.awt.Color(255, 255, 255));
        lblUserType.setText("User Type :");
        getContentPane().add(lblUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));

        lblCPassword.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        lblCPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblCPassword.setText("Confirm Password :");
        getContentPane().add(lblCPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        comboUserType.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        comboUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Employee" }));
        getContentPane().add(comboUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 190, 30));

        txtCPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtCPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 190, 30));

        txtsPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtsPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 190, 30));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        lblUserName.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setText("User Name :");
        getContentPane().add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loggflipped.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsUserNameActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        
        if (txtsUserName.getText().length()<1 || txtsPassword.getText().length()<1 || txtCPassword.getText().length()<1){
            JOptionPane.showMessageDialog(null,"Fill up all the fields");
        }
        
        else if(txtsPassword.getText() == null ? txtCPassword.getText() != null : !txtsPassword.getText().equals(txtCPassword.getText())){
                JOptionPane.showMessageDialog(null, "Password doesn't match");
            }
        
        else if ("Administrator".equals(comboUserType.getSelectedItem().toString()))
        {
            
            AdminValidate advalidate = new AdminValidate();
            advalidate.setVisible(true);
            advalidate.setLocationRelativeTo(null);
            this.dispose();
            
        }
        else{
            
            Database db = new Database();
            db.getDatabaseConnection();
            
            signup(txtsUserName.getText(), txtsPassword.getText(), comboUserType.getSelectedItem().toString());

        }
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Login login = new Login();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JComboBox<String> comboUserType;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCPassword;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSignUp;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserType;
    private javax.swing.JPasswordField txtCPassword;
    public static javax.swing.JPasswordField txtsPassword;
    public static javax.swing.JTextField txtsUserName;
    private javax.swing.JLabel user_icon;
    // End of variables declaration//GEN-END:variables

    private void signup(String UserName, String Password, String UserType) 
    {
        try{
            
     
            
            PreparedStatement ps = Database.con.prepareStatement("INSERT INTO login(UserName, Password, UserType) VALUES(?,?,?)");
            ps.setString(1,txtsUserName.getText());
            ps.setString(2,txtsPassword.getText());
            ps.setString(3,comboUserType.getSelectedItem().toString());
            
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Sign Up Successful !!");
            
            
            Menu menu = new Menu();
            menu.setVisible(true);
            menu.setLocationRelativeTo(null);
            this.dispose();
        }
        
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "ERROR");
        }
    }
}
